### ISSUE TITLE
8092 -改了propose price 后生成的pdf不需要approve就可以更新·【这个不行，需要先保存】

### ISSUE THREAD

**Issue by bensom1989** [bensom1989/hopefluentfeedback#13]
![image](https://user-images.githubusercontent.com/91407062/148489035-7fa6d102-9dd0-47c3-be60-36fdbd8836a4.png)

另外8091加上Propose price
![image](https://user-images.githubusercontent.com/91407062/148489109-5e61a950-1648-4d65-94a5-a1226e651ed2.png)

**Comment by jeawy** [comment]
【必须先保存才能在pdf中体现】
