### ISSUE TITLE
8092- Customised commission （New）

### ISSUE THREAD

**Issue by bensom1989** [bensom1989/hopefluentfeedback#2]
在project type部分增加customised commission 
![屏幕截图 2022-01-07 131934](https://user-images.githubusercontent.com/91407062/148480949-86833e05-d785-4db0-81be-47957c9dd7f0.png)

**Comment by jeawy** [comment]
【新增】增加这个干什么的

**Comment by bensom1989** [comment]
一直未回复这个commission是干什么的，需求不清楚，几次追问下也没有回复，先关掉。
