### ISSUE TITLE
Safari 浏览器自适应问题【修改】

### ISSUE THREAD

**Issue by bensom1989** [bensom1989/hopefluentfeedback#4]
![image](https://user-images.githubusercontent.com/91407062/148482532-9c7c4fe6-dfac-4f84-84e8-a2d697030562.png)

**Comment by jeawy** [comment]
？？？看不到菜单栏？【bug】

**Comment by bensom1989** [comment]
改天远程给他看看中这个bug吧，我在mac上也没有发现这个问题
